name: CMake

on:
  push:
    branches: [main, "feature/**", "release/**"]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PRESET: linux_release

jobs:
  ################################
  # Run Linter against code base #
  ################################
  lint:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-20.04 # TODO: Switch back to ununtu-latest when bug in github CI will be fixed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint All
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_CLANG_FORMAT: true

  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04
    env:
      CC: clang
      CXX: clang++

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake --preset ${{env.PRESET}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build/${{env.PRESET}} --parallel

      - name: Upload build directory to artefact
        uses: actions/upload-artifact@v4
        with:
          name: build_directory
          path: |
            ${{github.workspace}}/build/${{env.PRESET}}/algebra/tests/testVector
            ${{github.workspace}}/build/${{env.PRESET}}/algebra/tests/testMatrix

  tests:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Download build directory
        uses: actions/download-artifact@v4
        with:
          name: build_directory
          path: build

      - name: Update mode for test executable
        run: chmod +x ./build/testVector ./build/testMatrix

      - name: Test algebra module
        working-directory: build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      - name: Clean build directory artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build_directory
